### PR TITLE
test(broken)

### PR DESCRIPTION
**Pull request by nothingismagick**
Signed-off-by: Daniel Thompson-Yvetot <denjell@mailscript.com>

### CODE REVIEW

**Comment by nothingismagick** [comment]
Have to find out why clippy is running twice, it really shouldn't be, especially because the latter one seems to appear in a heisenbergian fashion... sometimes as `Build and run tests`, sometimes as `Format`. It does not affect us in any really meaningful way, other than potentially wasting resources and killing the planet one extra CI invocation at a time.

**Comment by nothingismagick** [comment]
@olexiyb - so in your opinion we should remove the other workflow files? I still think it is important to build and test on the matrix OS's

**Comment by olexiyb** [comment]
> @olexiyb - so in your opinion we should remove the other workflow files? I still think it is important to build and test on the matrix OS's

I would keep build and test for multiple platforms. But clippy and rustfmt can run using pre-commit.

**Comment by nothingismagick** [comment]
So I removed clippy and rustfmt workflows. Merging this in when it passes and will make a PR to upstream.

**Pull request merged**
